brew:
  enable_update: false
  enable_upgrade: false
  add_repositories:
#    - homebrew/dupes
#    - homebrew/versions
#    - homebrew/binary
#    - homebrew/cask-cask
    - starhoshi/starhoshicask
#    - homebrew/science
    - sanemat/font

  install_packages:
#    - caskroom/cask/brew-cask
    - koekeishiya/formulae/yabai
    - the_silver_searcher
    - coreutils
    - findutils
    - zsh
    - fish
    - bash
    - vim
    - neovim
    - tmux
    # pbcopy
    - reattach-to-user-namespace
    - git
    - mercurial
    - bzr
    - svn
    - tig
    - ghq
    - wget
    - rsync
    - curl
    - tree
    - openssl
    - readline
    - markdown
    - jq
    - peco
    - ctags
    - rbenv
    - ruby-build
    - opencv
    - htop-osx
    - ssh-copy-id
    - watch
    - gotags
    - httpie
    - pyenv
    - cmake
    - awscli
    - gh

  install_apps:
    - slack
    - alfred
    # - appcleaner
    # security soft
    # - avast-mac-security
    # simple editor
    # - coteditor
    # programing code refarence
    - dash
    # mac native docker
    - docker
    # - slack
    # - virtualbox
    - visual-studio-code
    #- iterm2
    # graph editor
    # can not install yed.
    # - yed
    # move and git tool
    - recordit
    # photo editor
    # - acorn
    # Video, Audio and Images converter
    # - adapter
    # Tiling window manager for OS X along the lines of xmonad and i3.
    # - amethyst
    # view animated gif
    # - unity
    # - gitbook-editor
    # - gitter
    - dbeaver-community
    # http://blog.livedoor.jp/fdaigo/rokuga
    # - background-music
